# Generated by Django 5.0 on 2024-07-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Divinite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("histoire", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ethnies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("langue", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("histoire", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("lieu", models.CharField(max_length=255)),
                ("statut", models.CharField(max_length=55)),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nbr_places_dispo", models.IntegerField()),
                (
                    "media_profil_url",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="photo_evenement/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("date_inauguration", models.DateField()),
                ("nom_concepteur", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("histoire", models.TextField(null=True)),
                ("visiteurs_annuels", models.IntegerField()),
                ("horaires", models.CharField(max_length=255)),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
                ("organisme_gestion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Musee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("superficie", models.FloatField()),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_fondation", models.DateField()),
                ("type_musee", models.CharField(max_length=255)),
                ("visiteurs_annuels", models.IntegerField()),
                ("horaires", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ParcNational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("visiteurs_annuels", models.IntegerField()),
                ("organisme_gestion", models.CharField(max_length=255)),
                ("superficie", models.FloatField()),
                ("horaires", models.CharField(max_length=255)),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("visiteurs_annuels", models.IntegerField()),
                ("organisme_gestion", models.CharField(max_length=255)),
                ("superficie", models.FloatField()),
                ("horaires", models.CharField(max_length=255)),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Royaume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("histoire", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("localisation", models.CharField(max_length=255)),
                ("date_classement", models.DateField()),
                ("description", models.TextField()),
                ("histoire", models.TextField(null=True)),
                ("visiteurs_annuels", models.IntegerField()),
                ("horaires", models.CharField(max_length=255)),
                ("prix_entree", models.DecimalField(decimal_places=2, max_digits=10)),
                ("organisme_gestion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Chant_Danse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=55)),
                ("auteur", models.CharField(max_length=55)),
                (
                    "type",
                    models.CharField(
                        choices=[("chant", "Chants"), ("danse", "Danses")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "ethnie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.ethnies",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjetExpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("origine", models.CharField(max_length=255)),
                ("date_appartenance", models.CharField(max_length=255)),
                (
                    "musee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.musee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EspeceArbre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_scientifique", models.CharField(max_length=255)),
                ("nom_commun", models.CharField(max_length=255)),
                ("reserves", models.ManyToManyField(blank=True, to="api.reserve")),
            ],
        ),
        migrations.CreateModel(
            name="EspeceAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_scientifique", models.CharField(max_length=255)),
                ("nom_commun", models.CharField(max_length=255)),
                (
                    "parcs_nationaux",
                    models.ManyToManyField(blank=True, to="api.parcnational"),
                ),
                ("reserves", models.ManyToManyField(blank=True, to="api.reserve")),
            ],
        ),
        migrations.AddField(
            model_name="ethnies",
            name="royaume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.royaume"
            ),
        ),
        migrations.CreateModel(
            name="ContenuMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("media_url", models.CharField(max_length=255)),
                (
                    "chant_danse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.chant_danse",
                    ),
                ),
                (
                    "monument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.monument",
                    ),
                ),
                (
                    "musee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.musee",
                    ),
                ),
                (
                    "parc_national",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.parcnational",
                    ),
                ),
                (
                    "reserve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.reserve",
                    ),
                ),
                (
                    "site_historique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.sitehistorique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sexe", models.CharField(max_length=10)),
                ("ethnie_id", models.CharField(blank=True, max_length=255, null=True)),
                ("premium", models.BooleanField(default=False)),
                (
                    "numero_momo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "num_carte_paiement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "media_profil_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos_profil/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=255)),
                ("verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                ("monuments_visites", models.ManyToManyField(to="api.monument")),
                ("musees_visites", models.ManyToManyField(to="api.musee")),
                ("parcs_visites", models.ManyToManyField(to="api.parcnational")),
                ("reserves_visites", models.ManyToManyField(to="api.reserve")),
                ("sites_visites", models.ManyToManyField(to="api.sitehistorique")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.evenement"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tradition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("histoire", models.TextField(null=True)),
                (
                    "ethnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.ethnies"
                    ),
                ),
            ],
        ),
    ]
