# Generated by Django 5.0 on 2024-06-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenumultimedia",
            name="monument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.monument",
            ),
        ),
        migrations.AlterField(
            model_name="contenumultimedia",
            name="musee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.musee",
            ),
        ),
        migrations.AlterField(
            model_name="contenumultimedia",
            name="parc_national",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.parcnational",
            ),
        ),
        migrations.AlterField(
            model_name="contenumultimedia",
            name="reserve",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.reserve",
            ),
        ),
        migrations.AlterField(
            model_name="contenumultimedia",
            name="site_historique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.sitehistorique",
            ),
        ),
        migrations.CreateModel(
            name="Chant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=55)),
                ("auteur", models.CharField(max_length=55)),
                ("description", models.CharField(max_length=255)),
                (
                    "ethnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.ethnie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contenumultimedia",
            name="chant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.chant",
            ),
        ),
        migrations.CreateModel(
            name="Danse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=55)),
                ("description", models.CharField(max_length=255)),
                (
                    "ethnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.ethnie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contenumultimedia",
            name="danse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.danse",
            ),
        ),
    ]
