# Generated by Django 5.0 on 2024-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="media_profil_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="monuments_visites",
            field=models.ManyToManyField(blank=True, null=True, to="api.monument"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="musees_visites",
            field=models.ManyToManyField(blank=True, null=True, to="api.musee"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="num_carte_paiement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="numero_momo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="parcs_visites",
            field=models.ManyToManyField(blank=True, null=True, to="api.parcnational"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="reserves_visites",
            field=models.ManyToManyField(blank=True, null=True, to="api.reserve"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="sites_visites",
            field=models.ManyToManyField(
                blank=True, null=True, to="api.sitehistorique"
            ),
        ),
    ]
