# Generated by Django 5.0 on 2024-07-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_utilisateur_media_profil_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="ethnie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ethnie",
            ),
        ),
    ]
