# Generated by Django 5.0 on 2024-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_actualites_objetvente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualites",
            name="media_url",
            field=models.ImageField(
                blank=True,
                default="photo_actualites/default.jpg",
                null=True,
                upload_to="photo_actualites/",
            ),
        ),
        migrations.AlterField(
            model_name="objetvente",
            name="media_url",
            field=models.ImageField(
                blank=True,
                default="photo_objetVente/default.jpg",
                null=True,
                upload_to="photo_objetVente/",
            ),
        ),
    ]
