# Generated by Django 5.0 on 2024-07-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contenumultimedia_monument_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="date_naissance",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="pays",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="ville",
        ),
        migrations.AlterField(
            model_name="divinite",
            name="histoire",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="monument",
            name="histoire",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="royaume",
            name="histoire",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sitehistorique",
            name="histoire",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="tradition",
            name="histoire",
            field=models.TextField(null=True),
        ),
    ]
