# Generated by Django 5.0 on 2024-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_utilisateur_ethnie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="ethnie",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
