# Generated by Django 5.0 on 2024-07-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_utilisateur_ethnie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="monuments_visites",
            field=models.ManyToManyField(to="api.monument"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="musees_visites",
            field=models.ManyToManyField(to="api.musee"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="parcs_visites",
            field=models.ManyToManyField(to="api.parcnational"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="reserves_visites",
            field=models.ManyToManyField(to="api.reserve"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="sites_visites",
            field=models.ManyToManyField(to="api.sitehistorique"),
        ),
    ]
