# Generated by Django 5.0 on 2024-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_utilisateur_monuments_visites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
