# Generated by Django 5.0 on 2024-07-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_utilisateur_is_active"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenumultimedia",
            name="chant",
        ),
        migrations.RemoveField(
            model_name="danse",
            name="ethnie",
        ),
        migrations.RemoveField(
            model_name="contenumultimedia",
            name="danse",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Chant_Danse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=55)),
                ("auteur", models.CharField(max_length=55)),
                (
                    "type",
                    models.CharField(
                        choices=[("chant", "Chants"), ("danse", "Danses")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "ethnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.ethnie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contenumultimedia",
            name="chant_danse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.chant_danse",
            ),
        ),
        migrations.DeleteModel(
            name="Chant",
        ),
        migrations.DeleteModel(
            name="Danse",
        ),
    ]
