# Generated by Django 5.0 on 2024-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_contenumultimedia_chant_remove_danse_ethnie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="media_profil_url",
            field=models.ImageField(blank=True, null=True, upload_to="photos_profil/"),
        ),
    ]
