# Generated by Django 5.0 on 2024-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_utilisateur_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
