# Generated by Django 5.0 on 2024-07-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_utilisateur_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="is_superuser",
        ),
    ]
