# Generated by Django 5.0 on 2024-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_utilisateur_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
